name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Print environment info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Git commit: ${{ github.sha }}"
          echo "Git ref: ${{ github.ref }}"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --verbose
          echo "Dependencies installed successfully"

      - name: Lint
        run: |
          echo "Running linting..."
          npm run lint
          echo "Linting completed successfully"

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"
          echo "Build output:"
          ls -la .next/ || echo "No .next directory found"

