name: E2E on Production

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Print environment info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Target URL: ${{ secrets.SITE_URL }}"
          echo "Working directory: $(pwd)"
          echo "Git commit: ${{ github.sha }}"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --verbose
          echo "Dependencies installed successfully"

      - name: Install Playwright Browsers
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps
          echo "Playwright browsers installed successfully"

      - name: Verify target URL accessibility
        env:
          BASE_URL: ${{ secrets.SITE_URL }}
        run: |
          echo "Checking target URL accessibility: $BASE_URL"
          curl -I "$BASE_URL" || echo "URL check failed, but continuing with tests"

      - name: Run Playwright tests against production
        env:
          BASE_URL: ${{ secrets.SITE_URL }}
        run: |
          echo "Running E2E tests against: $BASE_URL"
          npx playwright test -c playwright.config.ts --verbose
          echo "E2E tests completed"

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
