name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Print environment info
        run: |
          echo "=== Vercel Deployment Starting ==="
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Git commit: ${{ github.sha }}"
          echo "Git ref: ${{ github.ref }}"
          echo "Timestamp: $(date -Iseconds)"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --verbose
          echo "Dependencies installed successfully"

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"
          echo "Build output:"
          ls -la .next/ || echo "No .next directory found"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: '--prod'

      - name: Deployment complete
        run: |
          echo "=== Vercel Deployment Completed Successfully ==="
          echo "Timestamp: $(date -Iseconds)"

  no-op:
    runs-on: ubuntu-latest
    if: >-
      ${{ !(secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '') }}
    steps:
      - name: Log skipped deployment
        run: |
          echo "=== Vercel Deployment Skipped ==="
          echo "Reason: Required secrets are not configured"
          echo "Required secrets: VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID"
          echo "Timestamp: $(date -Iseconds)"

